language: python
python:
  # - "2.6"
  # - "2.7"
  # - "3.3"
  # - "3.4"
  - "3.5"
  - "3.6"
  # - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
# command to install dependencies
# before_install:
#   - sudo -H pip install --upgrade
env:
  - WITH_OPENCL=1
  - WITH_OPENCL=0

matrix:
  config:
    WITH_OPENCL=1:
      apt:
        packages:
        - python-pyopencl
        - python3-pyopencl
        - opencl-headers

      allow_failures:
      - python: '3.7-dev'
      - python: 'nightly'
    WITH_OPENCL=0:
      allow_failures:
      - python: '3.7-dev'
      - python: 'nightly'


install:
  - pip install --upgrade pip
  - pip install --ignore-installed setuptools
  - pip install --ignore-installed wheel
  - pip install --ignore-installed pytest-cov
  - pip install --ignore-installed pytest
  - python setup.py sdist
  - pip install -e .
  - export DISPLAY=:0.0
  # - python -c "import pyconrad.autoinit;pyconrad.edu().stanford.rsl.conrad.utils.Configuration.initConfig()"
# command to run tests
script:
  - python -c "import pyconrad"
  - pytest # or py.test for Python versions 3.5 and below
os:
  - linux
  # - osx

# addons:
#   apt:
#     packages:
    # - python-pyopencl
    # - python3-pyopencl
    # - opencl-headers
